# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d358889d3714f6ddb978fa392f6b89ea70c00418658ae13b27203e18ad9a07dd96c85bc9b6e74bbd32dd935e5f0e2fa84915c7b940369b5f1b2daf7e64f09248
  verifier_token: a22a9f69c32a40ed6462863a98c

test:
  secret_key_base: c5d0e39e58582b9ff4e7a186b859a35253b982a62a7d520bafddd70649f4e43df17a4e6dfcbb44d2c2787788c32d6d1dc79c75cf0d1c5e34a7d2d3597602f0f5
  verifier_token:
# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  verifier_token: <%= ENV["VERIFIER_TOKEN"] %>